# Generated by Django 3.2.2 on 2021-05-09 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenModel',
            fields=[
                ('almacenId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='id del almacen')),
                ('almacenNombre', models.CharField(db_column='nombre', help_text='Nombrecito del almacen', max_length=30, verbose_name='Nombre del almacen')),
                ('almacenDireccion', models.CharField(db_column='direccion', help_text='Direccion expresada en texto indicando Calle, Numero, Distrito, Provincia', max_length=100, verbose_name='Direccion del almacen')),
                ('almacenEstado', models.BooleanField(db_column='estado', default=True, help_text='Estado de disponibilidad del almacen', verbose_name='Estado del almacen')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
                'db_table': 'almacenes',
                'ordering': ['almacenNombre'],
                'unique_together': {('almacenNombre', 'almacenDireccion'), ('almacenDireccion', 'almacenEstado')},
            },
        ),
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('productoNombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
                ('productoDescripcion', models.CharField(db_column='Descripcion del producto', default='Por el momento no hay descripcion del producto', max_length=100)),
                ('productoPrecio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=5)),
                ('productoEstado', models.BooleanField(db_column='estado', default=True)),
                ('almacenId', models.ForeignKey(db_column='almacenes_id', on_delete=django.db.models.deletion.PROTECT, related_name='almacenProductos', to='inventario.almacenmodel')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
    ]
